apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hoppscotch-ingress
  namespace: hoppscotch
spec:
  ingressClassName: nginx
  rules:
  - host: hoppscotch-frontend.devbsfintech23.com
    http:
      paths:
      - backend:
          service:
            name: hoppscotch-frontend
            port:
              number: 3000
        path: /
        pathType: Prefix
  - host: hoppscotch-backend.devbsfintech23.com
    http:
      paths:
      - backend:
          service:
            name: hoppscotch-backend
            port:
              number: 3170
        path: /
        pathType: Prefix
  - host: hoppscotch-admin.devbsfintech23.com
    http:
      paths:
      - backend:
          service:
            name: hoppscotch-admin
            port:
              number: 3100
        path: /
        pathType: Prefix


